#!/bin/bash

FILES_TO_IGNORE=("index.spec.jsx" "constants.js" "styles.js" "styles.spec.js" "dataProcessor.js" "dataProcessor.spec.js" "mocks.js" "mocks.jsx")
DIRECTORIES_TO_IGNORE=("fastStatelessWrapper")

COMMAND="react-docgen src/components -o www/containers/props.json --pretty --resolver findAllComponentDefinitions"

for ignoreFile in ${FILES_TO_IGNORE[@]}; do
  COMMAND="$COMMAND --exclude $ignoreFile"
done

for ignoreDir in ${DIRECTORIES_TO_IGNORE[@]}; do
  COMMAND="$COMMAND --ignore $ignoreDir"
done

eval $COMMAND
