#!/bin/bash

# Exit if we're running a release
if [[ $RELEASE == true ]]; then exit 0; fi;

# Protect master from accidental commits.
echo "🔍  Checking branch isn't master."
branchName=$(git branch | grep '*' | sed 's/* //')
if [ $branchName == 'master' ]
then
  echo "💔  Cannot commit to master, please create a branch." && exit 1
fi
