#!/usr/bin/env node

const path = require('path');
const { execSync } = require('child_process');
let {
  coverage, file = process.env.npm_config_file, watch
} = require('minimist')(process.argv.slice(2));
if (coverage) process.env.npm_config_coverage = coverage;
process.env.TYPE = 'test';

if (file) {
  const projectRoot = execSync('npm root').toString().replace('node_modules', '').trim()

  const FORMAT = {
    BOLD: '\x1b[1m',
    RESET: '\x1b[0m',
    UNDERLINE: '\x1b[4m',
  }
  file = path.resolve(projectRoot, file);
  console.info(`${FORMAT.UNDERLINE}Running test${FORMAT.RESET}:${FORMAT.BOLD} ${file}${FORMAT.RESET}`);
  process.env.ADSLOT_TEST_FILE = file;
  // has to be done this way as karma removed the cli option to override config
}

// npm run test[:watch] --file=path [--coverage]
let cmd = 'karma start';
if (watch) cmd += ' --autoWatch=true --singleRun=false';
try {
  execSync(cmd, { stdio: [0, 1, 2] });
} catch (err) {
  process.exit(err.status);
}
