#!/usr/bin/env node

const path = require('path');
const { execSync } = require('child_process');

const TASK = 2;
const argv = require('minimist')(process.argv.slice(TASK + 1));
let { file = argv._.pop() } = argv;
if (file) {
  if (!path.isAbsolute(file)) {
    file = execSync('npm root').toString().replace('node_modules', file).trim()
  }
  const FORMAT = {
    UNDERLINE: '\x1b[4m',
    RESET: '\x1b[0m',
    BOLD: '\x1b[1m'
  }
  
  console.info(`${FORMAT.UNDERLINE}Running test${FORMAT.RESET}:${FORMAT.BOLD} ${file}${FORMAT.RESET}`); 
  process.env.ADSLOT_TEST_FILE = file;
  // has to be done this way as karma removed the cli option to override config
}

// npm run test[:watch] -- [--file=]path
switch (process.argv[TASK]) {
  case 'watch':
    exec('karma start --autoWatch=true --singleRun=false');
    break;
  default:
    exec('karma start');
}

function exec(cmd) {
  try {
    execSync(cmd, { stdio: [0, 1, 2] });
  } catch (err) {
    process.exit(err.status);
  }
}
